openapi: 3.2.0
info:
  title: BloodHound Azure Entities API
  contact:
    name: BloodHound Enterprise Support
    url: https://bloodhound.specterops.io/
    email: support@specterops.io
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v2
  description: This is the API that drives BloodHound Enterprise and Community Edition.
servers:
- url: /
  description: This is the base path for all endpoints, relative to the domain where the API is being hosted.
security:
- JWTBearerToken: []
- SignedRequest: []
  RequestDate: []
  HMACSignature: []
tags:
- name: Azure Entities
paths:
  /api/v2/azure/{entity_type}:
    parameters:
    - $ref: '#/components/parameters/header.prefer'
    - name: entity_type
      description: Entity Type
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: GetAzureEntity
      summary: Get Azure entity
      description: 'Retrieves entity information for the given Azure object ID.

        If `related_entity_type` parameter is not set, this endpoint will return information

        about a single entity. Using the `counts` boolean parameter will further modify the response.

        If `related_entity_type` parameter is set, this endpoint will return information about entities

        related to a single entity. The `type` parameter will morph the response data structure. The `list`

        value for the `type` parameter also accepts `skip` and `limit` parameters.'
      tags:
      - Azure Entities
      parameters:
      - name: object_id
        description: The object ID of the entity being operated on.
        in: query
        required: true
        schema:
          type: string
      - name: counts
        description: Returns related entity counts. Does not work with `related_entity_type` parameter.
        in: query
        schema:
          type: boolean
      - name: related_entity_type
        description: Flags the query to return related entity information based on the type passed.
        in: query
        schema:
          type: string
      - name: type
        description: The type of return data expected. Only works with `related_entity_type` parameter.
        in: query
        schema:
          type: string
          default: list
          enum:
          - list
          - graph
      - name: skip
        description: 'This query parameter is used for determining the number of objects to skip in pagination.

          Only compatible with `related_entity_type` and `type=list`

          '
        in: query
        schema:
          $ref: '#/components/schemas/api.params.query.skip'
      - name: limit
        description: 'This query parameter is used for setting an upper limit of objects returned in paginated responses.

          Only compatible with `related_entity_type` and `type=list`

          '
        in: query
        schema:
          type: integer
          minimum: 0
          default: 100
          description: The limit of results requested by the client.
      responses:
        '200':
          description: "This endpoint returns a polymorphic response dependent on the query parameters passed. Three\ndifferent response schemas are possible:\n- **entity** schema is used when `related_entity_type` is not set. Additional 'count' properties are\n  dependent on the type of entity being queried.\n- **related-list** schema is used when `related_entity_type` is set and `type` parameter is either\n  `list` or not set (it is the default), and it supports pagination.\n- **related-graph** schema is used when `related_entity_type` is set and `type=graph`.\n"
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  title: entity
                  description: 'This response is used when `related_entity_type` is not set. It returns information

                    about a single node. All node types will return with the basic node fields, but the

                    additional count properties are dependent on the kind of node returned. Setting

                    `counts=true` will populate those count details at the cost of performance.

                    '
                  properties:
                    data:
                      allOf:
                      - type: object
                        properties:
                          kind:
                            type: string
                          properties:
                            type: object
                            additionalProperties:
                              type: object
                      - type: object
                        additionalProperties:
                          type: integer
                - allOf:
                  - $ref: '#/components/schemas/api.response.pagination'
                  - type: object
                    title: related-list
                    description: 'This response is used when `related_entity_type` is set and the `type` parameter is

                      either `list` or not set (it is the default return type). It returns a list of related

                      entities and supports pagination parameters.

                      '
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            kind:
                              type: string
                            properties:
                              type: object
                              additionalProperties:
                                type: object
                            additionalProperties:
                              type: integer
                - allOf:
                  - $ref: '#/components/schemas/model.bh-graph.graph'
                  - title: related-graph
                    description: 'This response is used when `related_entity_type` is set and the `type` parameter is

                      set to `graph`. It returns graph data without a basic data response wrapper.

                      '
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/not-found'
        '429':
          $ref: '#/components/responses/too-many-requests'
        '500':
          $ref: '#/components/responses/internal-server-error'
components:
  responses:
    forbidden:
      description: '**Forbidden**

        This is most commonly caused by an authenticated client trying to

        access a resource that it does not have permission for.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 403
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: You do not have permission to access this resource
    internal-server-error:
      description: '**Internal Server Error**

        This is usually the result of either an unexpected database or application error.

        The client may try modifying or resending the request, but the error is likely not related to the client

        doing something wrong.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 500
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The request could not be handled due to an unexpected database error.
    unauthorized:
      description: '**Unauthorized**

        This endpoint failed an authentication requirement. Either the client tried to access

        a protected endpoint without being authenticated, or an auth validation failed (ex- invalid

        credentials or expired token).

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 401
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: login
              message: Unauthorized
    too-many-requests:
      description: '**Too Many Requests**

        The client has sent too many requests within a certain time window

        and tripped the rate limiting middleware.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 429
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: middleware
              message: Too many requests. Please try again later.
    not-found:
      description: '**Not Found**

        This error typically comes from operations where a valid ID was passed to the request

        to look up an entity but the entity could not be found.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 404
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The requested client could not be found.
    bad-request:
      description: '**Bad Request**

        This could be due to one of the following reasons:

        - JSON payload is missing or malformed

        - Path or query parameters are missing or invalid/malformed

        - The data sent is not valid (ex- sending a `string` in an `integer` field)

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/api.error-wrapper'
          example:
            http_status: 400
            timestamp: '2024-02-19T19:27:43.866Z'
            request_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
            errors:
            - context: clients
              message: The JSON payload could not be unmarshalled.
  schemas:
    api.params.query.limit:
      type: integer
      minimum: 0
      description: The limit of results requested by the client.
    model.bh-graph.graph:
      type: object
      additionalProperties:
        anyOf:
        - $ref: '#/components/schemas/model.bh-graph.node'
        - $ref: '#/components/schemas/model.bh-graph.edge'
    model.bh-graph.item:
      type: object
      properties:
        color:
          type: string
        fade:
          type: boolean
        data:
          type: object
          additionalProperties: true
        glyphs:
          type: array
          items:
            $ref: '#/components/schemas/model.bh-graph.glyph'
    model.bh-graph.glyph:
      type: object
      properties:
        angle:
          type: integer
        blink:
          type: boolean
        border:
          $ref: '#/components/schemas/model.bh-graph.item-border'
        color:
          type: string
        fontIcon:
          $ref: '#/components/schemas/model.bh-graph.font-icon'
        image:
          type: string
        label:
          $ref: '#/components/schemas/model.bh-graph.label'
        position:
          type: string
        radius:
          type: integer
        size:
          type: integer
    model.bh-graph.edge:
      allOf:
      - $ref: '#/components/schemas/model.bh-graph.item'
      - type: object
        properties:
          end1:
            $ref: '#/components/schemas/model.bh-graph.link-end'
          end2:
            $ref: '#/components/schemas/model.bh-graph.link-end'
          flow:
            type: object
            properties:
              velocity:
                type: integer
          id1:
            type: string
          id2:
            type: string
          label:
            $ref: '#/components/schemas/model.bh-graph.label'
          lineStyle:
            type: string
          width:
            type: integer
    api.error-detail:
      type: object
      properties:
        context:
          type: string
          description: The context in which the error took place
        message:
          type: string
          description: A human-readable description of the error
    model.bh-graph.item-border:
      type: object
      properties:
        color:
          type: string
    api.response.pagination:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          description: The total number of results.
        skip:
          $ref: '#/components/schemas/api.params.query.skip'
        limit:
          $ref: '#/components/schemas/api.params.query.limit'
    model.bh-graph.node:
      allOf:
      - $ref: '#/components/schemas/model.bh-graph.item'
      - type: object
        properties:
          border:
            type: object
            properties:
              color:
                type: string
              lineStyle:
                type: string
              width:
                type: integer
          coordinates:
            type: object
            properties:
              lat:
                type: integer
              lng:
                type: integer
          cutout:
            type: boolean
          fontIcon:
            $ref: '#/components/schemas/model.bh-graph.font-icon'
          halos:
            type: array
            items:
              type: object
              properties:
                color:
                  type: string
                radius:
                  type: integer
                width:
                  type: integer
          image:
            type: string
          label:
            type: object
            properties:
              backgroundColor:
                type: string
              bold:
                type: boolean
              center:
                type: boolean
              color:
                type: string
              fontFamily:
                type: string
              fontSize:
                type: integer
              text:
                type: string
          shape:
            type: string
          size:
            type: integer
    api.params.query.skip:
      type: integer
      minimum: 0
      description: The number of items to skip in a paginated response.
    api.error-wrapper:
      type: object
      description: ''
      properties:
        http_status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 600
        timestamp:
          type: string
          format: date-time
          description: The RFC-3339 timestamp in which the error response was sent
        request_id:
          type: string
          format: uuid
          description: The unique identifier of the request that failed
        errors:
          type: array
          items:
            $ref: '#/components/schemas/api.error-detail'
          description: The error(s) that occurred from processing the request
    model.bh-graph.label:
      type: object
      properties:
        bold:
          type: boolean
        color:
          type: string
        fontFamily:
          type: string
        text:
          type: string
    model.bh-graph.link-end:
      type: object
      properties:
        arrow:
          type: boolean
        backOff:
          type: integer
        color:
          type: string
        glyphs:
          type: array
          items:
            $ref: '#/components/schemas/model.bh-graph.glyph'
        label:
          $ref: '#/components/schemas/model.bh-graph.label'
    model.bh-graph.font-icon:
      type: object
      properties:
        color:
          type: string
        fontFamily:
          type: string
        text:
          type: string
  parameters:
    header.prefer:
      name: Prefer
      description: Prefer header, used to specify a custom timeout in seconds using the wait parameter as per RFC7240. Passing in wait=-1 bypasses all timeout limits when the feature is enabled.
      in: header
      required: false
      schema:
        type: string
        default: wait=30
        pattern: ^wait=(-1|[0-9]+)$
  securitySchemes:
    JWTBearerToken:
      description: '`Authorization: Bearer $JWT_TOKEN`

        '
      type: http
      scheme: bearer
      bearerFormat: JWT
    SignedRequest:
      description: '`Authorization: bhesignature $TOKEN_ID`

        '
      type: apiKey
      name: Authorization
      in: header
    RequestDate:
      description: '`RequestDate: $RFC3339_DATETIME`

        '
      type: apiKey
      name: RequestDate
      in: header
    HMACSignature:
      description: '`Signature: $BASE64ENCODED_HMAC_SIGNATURE`

        '
      type: apiKey
      name: Signature
      in: header
x-tagGroups:
- name: Community & Enterprise
  tags:
  - Auth
  - Roles
  - Permissions
  - API Tokens
  - BloodHound Users
  - Collectors
  - Collection Uploads
  - Custom Node Management
  - API Info
  - Search
  - Audit
  - Config
  - Asset Isolation
  - Graph
  - Azure Entities
  - AD Base Entities
  - Computers
  - Containers
  - Domains
  - GPOs
  - AIA CAs
  - Root CAs
  - Enterprise CAs
  - NT Auth Stores
  - Cert Templates
  - OUs
  - AD Users
  - Groups
  - Data Quality
  - Datapipe
  - Cypher
  - OpenGraph (Experimental)
- name: Enterprise Only
  tags:
  - EULA
  - BHE Users
  - Analysis
  - Client Ingest
  - Clients
  - Jobs
  - Tasks
  - Events (Schedules)
  - Attack Paths
  - Risk Posture
  - Meta Entities
  - Alerts
